export const GLOBAL_ACTIONS_TYPES = {
	START_LOADING: "START_LOADING",
	END_LOADING: "END_LOADING",
	SET_ERROR: "SET_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR",
	SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
	CLEAR_ERROR_MESSAGE: "CLEAR_ERROR_MESSAGE",
};
