export const DOGS_ACTIONS_TYPE = {
	GET_DOGS: "GET_DOGS",
	CLEAR_DOGS: "CLEAR_DOGS",
	ADD_DOG: "ADD_DOG",
	UPDATE_DOG: "UPDATE_DOG",
	REMOVE_DOG: "REMOVE_DOG",
	SAVE_IMAGE_DOG: "SAVE_IMAGE_DOG",
	UPDATE_IMAGE_DOG: "UPDATE_IMAGE_DOG",
	REMOVE_IMAGE_DOG: "REMOVE_IMAGE_DOG",
};
